import "@/styles/globals.css";
import type {AppProps} from "next/app";
import {Playfair_Display, Source_Sans_3} from "next/font/google";
import Head from "next/head";

const straightFont = Source_Sans_3({
    variable: "--font-family-straight"
})

const cursiveFont = Playfair_Display({
    variable: "--font-family-cursive"
})

export default function App({Component, pageProps}: AppProps) {
    return (
        <>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div
                className={`${straightFont.variable} ${cursiveFont.variable}`}
            >
                <main>
                    <Component {...pageProps} />
                </main>
            </div>
        </>
    )
}
